tox.ini

requirements-dev.txt contains tox itself, along with other unneeded stuff for running the tests.
This installs only the package dependencies + pytest in tox virtualenvs.

Avoid dev requirements in tox

---

.travis.yml

Once this is merged, when you push a tag (`git push --tags`) it will trigger a release to PyPI on the Travis build.
Note: this is WIP because it's missing the encrypted password, I'll update as soon as I get it.

Add draft config for PyPI deploy via Travis

---

extruct/service.py

The service is currently returning JSON content as `text/html` and I changed it to `application/json`.
I use a browser extension that highlights syntax when viewing source code files and it wasn't rendering JSON properly because of the response content type. :-)

Change service response content_type to JSON

---

extruct/rdfa.py

rdflib-jsonld already takes care of registering the plugins in [setup.py](https://github.com/RDFLib/rdflib-jsonld/blob/3563caf75295d9ee382b54fb2f812c6c3edffee3/setup.py#L97)

Remove rdflib json-ld serializer registration

---

extruct/rdfa.py

Trying to extract some RDFa from a site, I got AttributeError exception because of the lack of implementation of cloneNode and toxml. 
I've added both methods and now it's working.

Add cloneNode and toxml as some pages fail when extracting RDFa

---

extruct/service.py
extruct/tool.py
setup.py
tests/samples/songkick/tovestyrke.html
tests/samples/songkick/tovestyrke.json
tests/test_tool.py
tox.ini

Fixes https://github.com/scrapinghub/extruct/issues/27
This adds a command line tool called `extruct` that fetches a given URL and outputs the resulting metadata.
**Usage:**
$ extruct http://example.com
$ extruct --microdata http://example.com
$ extruct --jsonld http://example.com
$ extruct --rdfa http://example.com
$ extruct --jsonld --rdfa http://example.com

Add extruct command line tool

---

README.rst
setup.py

This adds the `cli` extra requirements, so that people can install the cli support by:
$ pip install extruct[cli]
It also documents the cli tool.

Add cli extra requirements and document command line tool

---

extruct/rdfa.py

`rdflib` displays this annoying log message when we import it. Thus, importing `extruct` gives us this:
>>> import extruct
INFO:rdflib:RDFLib Version: 4.2.2
This message is also displayed when we run `python -m extruct` and it's irrelevant to extruct, so this PR silences the `rdflib` logger before importing that module.

Silence rdflib logger to avoid message when importing

---

extruct/__init__.py
extruct/xmldom.py
tests/test_extruct.py

Resets a class variable after each extraction to prevent memory leak. More details in #59 .

Fix memory leak, issue-59

---

extruct/jsonld.py
tests/samples/custom.invalid/AllocateAction.001.html
tests/samples/custom.invalid/AllocateAction.001.jsonld
tests/samples/custom.invalid/JoinAction.001.html
tests/samples/custom.invalid/JoinAction.001.jsonld
tests/test_jsonld.py

See #62 for premise. This fixes the issue, and adds test-cases. The test cases duplicate the schema.org invalid files; I didn't want to edit them in place, as it would confuse their provenance.
I still wonder whether regex is the wrong way to fix prefixed/suffixed garbage, but a "correct" solution might be less efficient and harder to maintain. So perhaps it's best to shelve "correct" for now. :)

Fixing regex pattern to avoid removing comments from within valid JSON

---

extruct/uniform.py
tests/samples/misc/microformat_flat_test.json
tests/samples/misc/microformat_test.html
tests/samples/misc/microformat_test.json
tests/test_uniform.py

some microformat pages return an extra ``children`` field that is structured as a list of dicts with ``type`` and ``properties``, eg:
```
{ 'children': [ { 'properties': {'name': ['']},
'type': [ 'h-hidden-tablet',
'h-hidden-phone']},
{ 'properties': { 'name': [ 'aJ Styles '
'FastLane 2018 '
'15 x 17 Framed '
'Plaque w/ Ring '
'Canvas'],
'photo': [ '/on/demandware.static/-/Sites-main/default/dwa3227ee6/images/small/CN1148.jpg']},
'type': ['h-hidden-phone']}],
'properties': {'name': ['']},
'type': ['h-hidden-phone']}
```
This PR flattens children structure like the parent elements
```
{ 'children': [ { 'name': ['']},
'@type': [ 'h-hidden-tablet',
'h-hidden-phone'],
{ 'name': [ 'aJ Styles '
'FastLane 2018 '
'15 x 17 Framed '
'Plaque w/ Ring '
'Canvas'],
'photo': [ …
```

Flatten microformat children

---

README.rst
extruct/_extruct.py
extruct/jsonld.py
extruct/microformat.py
extruct/opengraph.py
extruct/rdfa.py
extruct/w3cmicrodata.py
tests/samples/schema.org/product_custom_url.json
tests/test_extruct.py
tests/test_microdata.py
tests/test_rdfa.py

Fixes #75 
Changes:
- ``base_url`` is used instead of ``url`` in ``extruct.extract``, ``url`` is still supported by deprecated
- individual extractors accpet ``base_url`` instead of ``url``, unused keyword arguments are removed
TODO:

Use base_url instead of url

---

requirements.txt
tests/samples/misc/microformat_flat_test.json
tests/samples/misc/microformat_test.json
tests/test_uniform.py

It seems that new version of the library for parsing microformats have been updated recently and it causes that three tests does not pass anymore. I did the following here:
- I verified why exactly the tests fails. 
* First of all `mf2py` seems to trim text in the content, so it means that signs of new line are removed. 
* Second thing is that in some cases the name property has been removed from output. To be honest I don't understand why it happened, especially that it is not removed every time. Do you think we should care about that and ask them about that?
- I believe that we can just use this new version so I fixed all tests.
- I fixed the version of library in `requirements.txt` to 1.1.0.

Fix tests for microformats

---

HISTORY.rst
README.rst
extruct/_extruct.py
extruct/w3cmicrodata.py
tests/__init__.py
tests/samples/schema.org/CreativeWork.001.html
tests/samples/schema.org/CreativeWork_flat_with_node_id.001.json
tests/samples/schema.org/product.html
tests/samples/schema.org/product_custom_url_and_node_id.json
tests/test_extruct.py
tests/test_extruct_uniform.py

I've added here an option to return html nodes in the result of `extract` method. The motivation of that change is to be able to parse additionally html node in case the metadata item is not fully consistent with the standard.
I checked in which syntaxes I can add that option and it seems it's possible only for microdata. 
I did here the following:
- Added returning node in microdata parser.
- Added option to `extract` method for returning html node.
- Updated tests. Please take a look in tests, because I had to do replacing of node reference with the identifier of node in order to have test case in json. Let me please know if you do not like it. 
TODO:

[MRG+1] Add option to return html node during extraction

---

.travis.yml
extruct/_extruct.py
extruct/jsonld.py
extruct/tool.py
setup.py
tests/test_extruct.py
tox.ini

* added Python 3.7 to tests
* fix Python 3.7 warnings
* improve DeprecationWarning, so that it points to a caller code

better Python 3.7 support

---

extruct/_extruct.py
tests/test_extruct.py

as explained in #99 errors='ignore' was not universal. 
I wanted to add a test but I don't know how to test exceptions

ignore any exception if errors='ignore'

---

extruct/w3cmicrodata.py
tests/samples/schema.org/product-ref.html
tests/samples/schema.org/product-ref.json
tests/samples/w3c/microdata.5.3.json
tests/test_microdata.py

Extruct deals wrongly with elements referenced by `itemref` if the referenced element also include other items defined inside with `itemscope`. For example:
```html
<html>
<body>
<div id="product" itemscope itemtype="http://schema.org/Product" itemref="other-product-properties">
<span itemprop="name">Executive Anvil</span>
</div>
<div id="other-product-properties">
<div itemscope itemtype="http://schema.org/Product" itemprop="related_products">
<span itemprop="name">REL PROD 1</span>
</div>
</div>
</body>
</html>
```
Is extracted as (see the duplicate name and the extra image):
```py
[{'@context': 'http://schema.org',
'@type': 'Product',
'image': ['img2.jpg', 'rel-prod-1.jpg', 'img1.jpg'],
'name': ['REL PROD 1', 'Executive Anvil'],
'related_products': {'@type': 'Product',
'image': …
```

Avoid including itemprop from child itemscopes when using itemref

---

extruct/uniform.py
tests/samples/songkick/elysianfields.html
tests/samples/songkick/elysianfields.json
tests/test_extruct.py
tests/test_uniform.py

Some pages contain a duplicated definition of some properties like "og:image". See the following pages:
https://nerdist.com/article/star-wars-cast-reylo-episode-ix/
https://cleantechnica.com/2019/04/16/fukushimas-final-costs-will-approach-one-trillion-dollars-just-for-nuclear-disaster/
Extruct default behaviour seems to be keep the last one, meanwhile Facebook default behaviour seems to be keep the first one according to results at the developer tool (see https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnerdist.com%2Farticle%2Fstar-wars-cast-reylo-episode-ix%2F for an example).
Extruct should mimic Facebook behaviour so this PR is reverting the priorities when flattening OpenGraph properties.

Reverse priorities for repeated properties in uniform format for opengraph

---

extruct/w3cmicrodata.py
requirements.txt
setup.py

This is an unfinished fix for https://github.com/scrapinghub/extruct/issues/113, please don't merge. I've opened the PR just to share initial code. It has these problems:
* cleaning can be too aggressive, e.g. `<style>` elements are removed. This may cause missing extractions, if microdata is set on these elements.
* tests are failing (I haven't looked at them - probably the fix is not correct at all :)
The problem with not cleaning HTML tree once is that it could make algorithm O(N^2) - but maybe that's fine.

[wip] use html_text to get element text content in microdata

---

extruct/uniform.py
tests/test_uniform.py

Solves https://github.com/scrapinghub/extruct/issues/117

OpenGraph skipping empty for properties with values on flattening

---

.travis.yml
setup.py

recent lxml doesn't work with Python 3.4, and Python 3.4 is unsupported.
Tests are failing in Python 3.4 because recent lxml can't be installed.

drop Python 3.4 support

---

extruct/rdfa.py
tests/samples/misc/expanded_OG_support_test.html
tests/samples/misc/expanded_OG_support_test.json
tests/test_rdfa.py

Fixes #31 
The merge would result in identifying expanded opengraph metadata properties and replacing them with their corresponding namespaces by adding appropriate prefix to the html tag

Support for expanded opengraph metadata

---

extruct/w3cmicrodata.py

Previously, get_docid had quadratic complexity, as for each node, it
counted it's position in the tree iterating over all previous nodes.
Here we fix this by computing get_docid in the same way for the first
element, and then incrementing it by one, which gives the same result
but has linear complexity and is much faster (e.g. bringing time from
190+ s to 6 s on example from GH-147).
Other discarded implementation options:
- using some other identifier for the node - this would break backwards
compatibility, as this property was exposed and documented at least in
the code
- instead of calling get_docid for the first element, just iterate over
the whole document (from root) to build ids - this is less
efficient in case we call extraction on a part of the document.
TODO:

Fast get_docid for microdata parser (fixes GH-147)

---

extruct/jsonld.py
requirements.txt
setup.py
tests/samples/custom.invalid/JSONLD_with_JS_comment.html
tests/samples/custom.invalid/JSONLD_with_JS_comment.jsonld
tests/test_jsonld.py

I encountered the issue of parsing `json-ld` with JS comments. Finally, I found the `jstyleson` package that could solve.
```
1. comment the key-value pair 
2. comment occurs after the key-value pair 
{
'\t//"interactionCount": "", // 文章互動數 \r\n'
'\t\t"height": "1000", // 高度， 有預設或是的高度\r\n'
}
```

feat: add parser for JSON with JS comment

---

README.rst

Document how to make releases

---

.github/workflows/python-package.yml

https://tox.readthedocs.io/en/latest/example/basic.html#a-simple-tox-ini-default-environments - as suggested by @kmike here https://github.com/scrapinghub/extruct/pull/164#discussion_r541546548

Remove an ugly way to pass python version to tox

---

README.rst
requirements-dev.txt
tox.ini

If it does not render, we won't be able to publish a release on PyPI, see https://github.com/scrapinghub/extruct/pull/168#issuecomment-751741909

Fix README, make sure it renders

---

README.rst

It only worked after I added quotes around the extruct[cli] --> 'extruct[cli]'

add quotes around extruct[cli]

---

extruct/rdfa.py

This PR aims to close #176, where it's described how the latest `rdflib` dependency may not always return bytes, thus fresh installations would raise errors.
The changes here aim to be backward compatible with older versions of `rdflib`.  
This was tested as follows:
1) Setup this package
2) Install rdflib 6.0.0: `pip install rdflib==6.0.0`
3) run the test and see them failing: (truncated to only failing tests)
```python
cydanil@inara ~/extruct> pytest -vv tests                                                                                                                                                                                master
============================================================================================================ test session starts …
```

Check for type when extracting RDFa content

---

.gitattributes

The current project stats show that it is mostly HTML due to an incorrectly set `.gitattributes`. This pull request fixes this.

Fix linguist stats

---

.git-blame-ignore-revs

Follow-up on https://github.com/scrapinghub/extruct/pull/201

create .git-blame-ignore-revs to contain commits due to black and isort

---

.github/workflows/python-package.yml
README.rst
extruct/_extruct.py
setup.py
tests/test_extruct.py
tests/test_extruct_uniform.py
tox.ini

A small performance improvement: allow receiving an external tree into extruct.
Also bump the default Python version to 3.9, hope that's OK.

Allow receiving an external tree, drop python 3.7

---

extruct/xmldom.py
requirements.txt
tests/samples/misc/microformat_flat_test.json
tests/samples/misc/microformat_test.json
tests/test_uniform.py

lxml 5.1.0 removed _ElementStringResult which we use during dom traversal. This PR attempts to import _ElementStringResult as usual, but falls back to defining it explicitly if the import fails. This fixes https://github.com/scrapinghub/extruct/issues/215
I chose to attempt to import first to preserve existing behavior if an older version of lxml is installed.
Additionally, we use the lxml HTML cleaner, which is now in its own separate package. Due to this I've added the optional html_clean package to the requirements.txt. As noted below, this raises a warning if using lxml < 5.2.0, but otherwise doesn't impact older versions.

fix: Add Support for lxml >= 5.2.0

---

extruct/rdfa.py

Fix this issue :
```
/usr/lib/python3/dist-packages/extruct/rdfa.py:88: SyntaxWarning: invalid escape sequence '\s'
match = re.search(prefix + ": [^\s]+", head_element.get("prefix"))
```

Fix SyntaxWarning in #213

---

extruct/jsonld.py
extruct/rdfa.py
extruct/utils.py
extruct/xmldom.py
setup.py
tests/__init__.py
tests/test_dublincore.py
tests/test_extruct.py
tests/test_extruct_uniform.py
tests/test_jsonld.py
tests/test_microdata.py
tests/test_microformat.py
tests/test_opengraph.py
tests/test_rdfa.py

Not required for python 3. Every file is utf8.
#221

fix: remove py2 utf8 encoding

---

extruct/jsonld.py
extruct/microformat.py
extruct/w3cmicrodata.py

feat: use `yield from` syntax

---

.github/workflows/python-package.yml
.pre-commit-config.yaml
extruct/w3cmicrodata.py

* update pre-commit dependencies
* add pyupgrade to avoid outdated python code / styles
closes #221

feat: add `pyupgrade` to `pre-commit`

---

extruct/jsonld.py
tests/test_jsonld.py

Skipping empty JSON-LD scripts prevents parsing issues with blank data.

Skip empty JSON-LD scripts by trimming and skipping empty input
